version: "3.7"

services:
    auth-server:
        image: auth-server
        build:
            context: .
            dockerfile: ./auth/Dockerfile
        environment: 
            DB_HOST: auth-db
            DB_USER: auth-user
            DB_PASSWORD: auth-pass
            DB_NAME: db
            LOG_LEVEL: debug
        depends_on: 
            - auth-db
        volumes: 
            - ./volumes/certs:/var/lib/certs

    auth-db:
        image: mongo
        volumes:
            - ./volumes/data/auth:/data/db
            - ./scripts/init-auth-db.js:/docker-entrypoint-initdb.d/mongo-init.js
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        command: mongod --port 27017 --bind_ip_all
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - auth-db
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_SERVER: auth-db

    api-server:
        image: api-server
        build:
            context: .
            dockerfile: ./api/Dockerfile
        environment: 
            DB_HOST: api-db
            DB_USER: api_user
            DB_PASSWORD: api_pass
            DB_NAME: db
            LOG_LEVEL: debug
        depends_on: 
            - auth-server
            - api-db
        volumes: 
            - ./volumes/certs:/var/lib/certs

    api-db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./scripts/init-api-db.sql:/docker-entrypoint-initdb.d/init.sql
            - ./volumes/data/api:/var/lib/postgresql/data

    pgadmin: 
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 80
            PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers.json
        ports:
            - 8080:80
        volumes:
            - ./volumes/data/pgadmin:/var/lib/pgadmin
            - ./config/pgadmin-servers.json:/var/lib/pgadmin/servers.json
        depends_on: 
            - api-db

    minica-ssl-certs:
        image: twalter/minica
        command: --ca-cert ca.pem --ca-key ca-key.pem --domains localhost
        volumes: 
            - ./volumes/certs/ssl:/output

    openssl-dhparams:
        image: frapsoft/openssl
        command: dhparam -out /export/dhparam.pem 1024
        volumes:
            - ./volumes/certs/ssl:/export

    nginx:
        image: nginx:mainline-alpine
        ports: 
            - 8000:80
            - 443:443
        volumes:
            - ./volumes/certs/ssl:/etc/nginx-certs
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - api-server
            - auth-server
            - minica-ssl-certs
            - openssl-dhparams
