version: "3.7"

services:
    auth-server:
        image: auth-server
        build:
            context: .
            dockerfile: ./auth/Dockerfile
        ports:
            - 8889:3000
        environment: 
            DB_HOST: auth-db
            DB_USER: auth-user
            DB_PASSWORD: auth-pass
            DB_NAME: db
            LOG_LEVEL: debug
        depends_on: 
            - auth-db
        volumes: 
            - ./volumes/certs:/var/lib/certs

    auth-db:
        image: mongo
        volumes:
            - ./volumes/data/auth:/data/db
            - ./scripts/init-auth-db.js:/docker-entrypoint-initdb.d/mongo-init.js
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        command: mongod --port 27017 --bind_ip_all
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - auth-db
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_SERVER: auth-db

    app-server:
        image: app-server
        build:
            context: .
            dockerfile: ./app/Dockerfile
        environment: 
            DB_HOST: app-db
            DB_USER: app_user
            DB_PASSWORD: app_pass
            DB_NAME: db
            LOG_LEVEL: debug
        ports:
            - 8888:3000
        depends_on: 
            - auth-server
            - app-db
        volumes: 
            - ./volumes/certs:/var/lib/certs

    app-db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./scripts/init-app-db.sql:/docker-entrypoint-initdb.d/init.sql
            - ./volumes/data/app:/var/lib/postgresql/data

    pgadmin: 
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 80
            PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers.json
        ports:
            - 8080:80
        volumes:
            - ./volumes/data/pgadmin:/var/lib/pgadmin
            - ./scripts/pgadmin-servers.json:/var/lib/pgadmin/servers.json
        depends_on: 
            - app-db
    